### ISSUE TITLE
No trackers appear in SteamVR

### ISSUE THREAD

**Issue by GoXii13** [justinliang1020/AirPose#2]
Seems to make no difference when the program is started or what order. AirPose executeable started without admin privileges or compatibility mode, on Windows 10 Pro. 

Multiple tracked sources set to true in SteamVR.

Done on Quest 2. Persists with SteamVR beta and production version.

**Comment by justinliang1020** [comment]
Airpose may be blocked on SteamVR? Go to SteamVR settings -> Startup/shutdown -> Mange Add-ons, and make sure airpose is unblocked.
![image](https://user-images.githubusercontent.com/54543035/123554145-53e1ff80-d744-11eb-9ab9-6aae3bc41c14.png)


If that doesn't work let me know.

Thanks,
Justin

**Comment by GoXii13** [comment]
Thank you for the quick reply!

It doesn't appear to be blocked by SteamVR.
![Capture7](https://user-images.githubusercontent.com/86567415/123555250-8bf03f00-d752-11eb-8ef0-ddd595bceaab.PNG)

**Comment by justinliang1020** [comment]
Hmm not sure what's causing this issue. Can you go to steam folder -> logs -> vrserver (should be a .txt file) and send your vrserver.txt ? This should contain some debug info that may help solve this issue.

Thanks for your patience!

**Comment by GoXii13** [comment]
Sure thing,
[vrserver.txt](https://github.com/justinliang1020/AirPose/files/6722257/vrserver.txt)

Just happy to see something nice you've made

**Comment by justinliang1020** [comment]
I think I may have found the problem.

I updated the installation instructions to say to specifically copy-paste the airpose folder found in the unzipped airpose.release folder, into your drivers directory. In addition, I updated the zip file to be named airpose.release.7z to differentiate it from the airpose folder contained within it.

Sorry, this was an error on my end as I made my installation instructions vague. Let me know if this solution works or still doesn't work.

**Comment by GoXii13** [comment]
Ah, yes I'd tried both ways just in case before. Though there's no harm in trying again.

**Comment by ayewyn** [comment]
I'm having the same issue, no trackers show up in steam VR, also using quest 2 and windows 10.
In the log I got 
"Tue Jun 29 2021 13:15:32.320 - Unable to load driver shared library airpose from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\airpose\bin\win64\driver_airpose.dll. Error Code (126)
Tue Jun 29 2021 13:15:32.321 - ASSERT: "DriverManager airpose load error 126" at c:\buildslave\steamvr_rel_win64\build\src\common\vrcommon\drivermanager.cpp:404.
Tue Jun 29 2021 13:15:32.334 - Connecting client (SteamVR_Namespace) app container status: 1
Tue Jun 29 2021 13:15:32.334 - CSharedResourceNamespaceServer sent namespace data: 13356
Tue Jun 29 2021 13:15:32.347 - Connecting client (VR_ServerPipe_13356) app container status: 1
Tue Jun 29 2021 13:15:32.356 - Closing pipe VR_ServerPipe_13356 because it was broken from the other end
Tue Jun 29 2021 13:15:32.356 - Process  disconnected (Thread(0x0000029E33BF3A50/0x000)
Tue Jun 29 2021 13:15:32.611 - Unable to load driver airpose because of error VRInitError_Init_FileNotFound(103). Skipping."

I copied the folder from the unzipped package to the steam folder as instructed.

On the up side the app seems to be tracking me really well, I look forward to trying it out when this issue is sorted.

**Comment by justinliang1020** [comment]
Yea this seems like a tricky issue to resolve. https://windowsreport.com/dll-error-126-127-fix/

It's probably due to some missing dependency or outdated driver, but it's not super apparent just from the debug text what it is. I'll be leaving this issue open and continue to research.

**Comment by GoXii13** [comment]
Could take a look at this stackoverflow solution: https://stackoverflow.com/a/14362289

Maybe we could patch together what we need to fix with the utility linked in this answer.

Otherwise, the only tips are set build target to release win64.

**Comment by ayewyn** [comment]
If you need us to try anything on our side just let us know. Happy to help.

**Comment by d4nielrx** [comment]
does this help https://github.com/ValveSoftware/openvr/issues/1311

**Comment by justinliang1020** [comment]
I updated the build to use release instead of debug, as mentioned in the following replies.

Let me know if this new release works!
 

> does this help [ValveSoftware/openvr#1311](https://github.com/ValveSoftware/openvr/issues/1311)



> Could take a look at this stackoverflow solution: https://stackoverflow.com/a/14362289
> 
> Maybe we could patch together what we need to fix with the utility linked in this answer.
> 
> Otherwise, the only tips are set build target to release win64.

Thanks

**Comment by GoXii13** [comment]
Ah, I'm free to test it out soon, you just have to rebuild and commit, right?

**Comment by justinliang1020** [comment]
Yea, I just updated the release file (https://github.com/justinliang1020/AirPose/releases/tag/v0.1) so it doesn't appear as a commit to the repo.

**Comment by ayewyn** [comment]
> I updated the build to use release instead of debug, as mentioned in the following replies.
> 
> Let me know if this new release works!

It works! Great job. The tracking can be a bit rough at times but this is fantastic progress.
![VRChat_1280x720_2021-07-03_21-07-53 841](https://user-images.githubusercontent.com/86688438/124373210-282faf80-dc45-11eb-88a8-4e063ab81141.png)

**Comment by d4nielrx** [comment]
> > I updated the build to use release instead of debug, as mentioned in the following replies.
> > Let me know if this new release works!
> 
> It works! Great job. The tracking can be a bit rough at times but this is fantastic progress.
> ![VRChat_1280x720_2021-07-03_21-07-53 841](https://user-images.githubusercontent.com/86688438/124373210-282faf80-dc45-11eb-88a8-4e063ab81141.png)

Was your tracking very glitchy and jittery? Mine was pretty much unusable.

**Comment by ayewyn** [comment]
> Was your tracking very glitchy and jittery? Mine was pretty much unusable.

It could definitely use some fine tuning, but I am able to move my legs and hips and lift my feet. Turning around doesn't work but that is expected. I'd say it is 80% of the way there for 180 FBT, which is impressive for only needing a webcam.

You might want to try different lighting set ups and camera positions, it took me a few tries to get it right.

**Comment by d4nielrx** [comment]
> > Was your tracking very glitchy and jittery? Mine was pretty much unusable.
> 
> It could definitely use some fine tuning, but I am able to move my legs and hips and lift my feet. Turning around doesn't work but that is expected. I'd say it is 80% of the way there for 180 FBT, which is impressive for only needing a webcam.
> 
> You might want to try different lighting set ups and camera positions, it took me a few tries to get it right.

Did you try sitting down?

**Comment by justinliang1020** [comment]
Yea the tracking is definitely quite jittery. Some of the jitter at least on my end is compensated once you get into a game like VRChat which has some motion smoothing on avatars.

You should be able to lift move your feet and hips horizontally/vertically; however depth is lacking. It also only works when facing towards the camera. In addition, make sure to stand still for a few seconds while steamVR initiates in order to calibrate properly.

As a whole I see full body tracking on a spectrum of convenience(cost, ease of use, comfort) to tracking quality(accuracy, depth tracking, latency). Vive trackers are low convenience, but high tracking quality. Solutions like apriltag VR and Kinect VR are mid convenience, mid tracking quality. I went for a high convenience, low tracking quality solution when building airpose.

However in the future as pose estimation algorithms improve, I hope to improve it's accuracy.

**Comment by justinliang1020** [comment]
> > > Was your tracking very glitchy and jittery? Mine was pretty much unusable.
> > 
> > It could definitely use some fine tuning, but I am able to move my legs and hips and lift my feet. Turning around doesn't work but that is expected. I'd say it is 80% of the way there for 180 FBT, which is impressive for only needing a webcam.
> > 
> > You might want to try different lighting set ups and camera positions, it took me a few tries to get it right.
> 
> Did you try sitting down? 

The pose estimation algorithm I'm using isn't robust enough to handle sitting down, so it breaks when doing that. I tried to hardcode a solution for sitting, but I'm not sure if it's flexible enough to work on different camera setups/people.

**Comment by justinliang1020** [comment]
I will be closing the issue now since it's specifically for the trackers bug.

**Comment by d4nielrx** [comment]
I dunno if you seen mocapforall? But they use apriltag trackers with pose esitmatin, for depth I wonder if that’s possible with this, the only issue with mocapforall is very resource heavy and also expensive.
